[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend/"
buildCommand = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache"
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[[services]]
name = "frontend"
source = "frontend/"
buildCommand = "npm ci && npm run build"
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"

[[services]]
name = "database"
image = "mysql:8.0"
