[variables]
PHP_VERSION = "8.3"

[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_sqlite"]

[phases.install]
cmds = ["composer install --no-dev --no-interaction"]

[phases.build]
cmds = [
  "mkdir -p database",
  "touch database/database.sqlite",
  "echo 'APP_KEY=base64:z0a3Q3u2vGAZ0dYflkfr2ELJ/CR7A6HjH44IMcpzjGo=' > .env",
  "echo 'DB_CONNECTION=sqlite' >> .env",
  "echo 'DB_DATABASE=/opt/render/project/src/database/database.sqlite' >> .env"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
