[variables]
PHP_VERSION = "8.3"

[phases.setup]
nixPkgs = ["php83", "php83Extensions.bcmath", "php83Extensions.ctype", "php83Extensions.curl", "php83Extensions.dom", "php83Extensions.fileinfo", "php83Extensions.filter", "php83Extensions.hash", "php83Extensions.mbstring", "php83Extensions.openssl", "php83Extensions.pcre", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.session", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.zip"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs"
]

[phases.build]
cmds = [
  "php artisan config:cache || true",
  "php artisan route:cache || true",
  "php artisan view:cache || true"
]

[phases.start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
