[variables]
PHP_VERSION = "8.3"

[phases.setup]
nixPkgs = [
    "php83", 
    "php83Extensions.bcmath",
    "php83Extensions.ctype",
    "php83Extensions.curl",
    "php83Extensions.dom",
    "php83Extensions.fileinfo",
    "php83Extensions.filter",
    "php83Extensions.hash",
    "php83Extensions.mbstring",
    "php83Extensions.openssl",
    "php83Extensions.pcre",
    "php83Extensions.pdo", 
    "php83Extensions.pdo_sqlite",
    "php83Extensions.session",
    "php83Extensions.tokenizer",
    "php83Extensions.xml",
    "php83Extensions.zip"
]

[phases.install]
cmds = ["composer install --no-dev --no-interaction --optimize-autoloader"]

[phases.build]
cmds = [
  "mkdir -p database storage/logs storage/framework/cache storage/framework/sessions storage/framework/views",
  "touch database/database.sqlite",
  "chmod -R 775 storage bootstrap/cache database",
  "echo 'APP_NAME=VidaduAcademy' > .env",
  "echo 'APP_ENV=production' >> .env",
  "echo 'APP_KEY=base64:z0a3Q3u2vGAZ0dYflkfr2ELJ/CR7A6HjH44IMcpzjGo=' >> .env",
  "echo 'APP_DEBUG=false' >> .env",
  "echo 'APP_URL=https://vidaduacademy.onrender.com' >> .env",
  "echo 'DB_CONNECTION=sqlite' >> .env",
  "echo 'DB_DATABASE=/opt/render/project/src/database/database.sqlite' >> .env",
  "echo 'CACHE_DRIVER=file' >> .env",
  "echo 'SESSION_DRIVER=database' >> .env",
  "echo 'QUEUE_CONNECTION=database' >> .env",
  "php artisan migrate --force || true",
  "php artisan config:cache || true",
  "php artisan route:cache || true",
  "php artisan view:cache || true"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
