[variables]
PHP_VERSION = "8.1"

[phases.setup]
nixPkgs = ["php81", "php81Extensions.bcmath", "php81Extensions.ctype", "php81Extensions.curl", "php81Extensions.dom", "php81Extensions.fileinfo", "php81Extensions.filter", "php81Extensions.hash", "php81Extensions.mbstring", "php81Extensions.openssl", "php81Extensions.pcre", "php81Extensions.pdo", "php81Extensions.pdo_mysql", "php81Extensions.session", "php81Extensions.tokenizer", "php81Extensions.xml", "php81Extensions.zip"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs"
]

[phases.build]
cmds = [
  "php artisan config:cache || true",
  "php artisan route:cache || true",
  "php artisan view:cache || true"
]

[phases.start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
